# Prepended configuration: first level key is an extension name.

ibexa:
  system:
    default:
      embedding_models:
        text-embedding-004-small:
          name: 'gemini-embedding-001'
          dimensions: 768
          field_suffix: 'gemini_small'
          embedding_provider: 'ibexa_gemini'
        text-embedding-004-large:
          name: 'gemini-embedding-001'
          dimensions: 3072
          field_suffix: 'gemini_large'
          embedding_provider: 'ibexa_gemini'
        text-embedding-004-default:
          name: 'gemini-embedding-001'
          dimensions: 1536
          field_suffix: 'gemini_ada'
          embedding_provider: 'ibexa_gemini'
      default_embedding_model: 'gemini-embedding-001'